#!/usr/bin/env python3
"""Generate tools/mock_api.luau: real per-class property names from the Roblox
API definitions, so the headless mock can reject an invalid property write the
way Roblox does.

This exists because of a live bug: `ScrollBarImage = ""` shipped and crashed in
a real executor. Nothing caught it -- Util.Create assigns by dynamic key so the
typechecker cannot see the property name, and the mock happily accepted any
write. A permissive mock produces false PASSES, which is worse than useless.

    python tools/gen_mock_api.py

Re-run after updating tools/globalTypes.d.luau.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFS = ROOT / "tools" / "globalTypes.d.luau"
OUT = ROOT / "tools" / "mock_api.luau"

# Classes Sable instantiates, plus the ones the mock itself fabricates.
CLASSES = [
    "CanvasGroup", "Frame", "ScreenGui", "ScrollingFrame", "TextBox",
    "TextButton", "TextLabel", "UIGradient", "UIListLayout", "UIPadding",
    "UIStroke", "UICorner", "ImageLabel", "ImageButton", "Folder",
    "InputObject", "Player", "PlayerGui", "CoreGui",
]

HEADER = re.compile(r"^declare (?:class|extern type) (\w+)(?: extends (\w+))? with\s*$")
PROP = re.compile(r"^\t(\w+):\s")
FUNC = re.compile(r"^\tfunction ")


def parse(text: str):
    """class -> (parent, {property names})"""
    classes: dict[str, tuple[str | None, set[str]]] = {}
    current = None
    for line in text.splitlines():
        header = HEADER.match(line)
        if header:
            name, parent = header.group(1), header.group(2)
            classes[name] = (parent, set())
            current = name
            continue
        if current is None:
            continue
        if line == "end":
            current = None
            continue
        if FUNC.match(line):
            continue
        prop = PROP.match(line)
        if prop:
            classes[current][1].add(prop.group(1))
    return classes


def resolve(classes, name: str) -> set[str]:
    """Properties including everything inherited."""
    out: set[str] = set()
    seen: set[str] = set()
    cur: str | None = name
    while cur and cur in classes and cur not in seen:
        seen.add(cur)
        parent, props = classes[cur]
        out |= props
        cur = parent
    return out


def main() -> int:
    if not DEFS.exists():
        print(f"missing {DEFS} -- run tools/bootstrap.ps1", file=sys.stderr)
        return 2

    classes = parse(DEFS.read_text(encoding="utf-8"))

    missing = [c for c in CLASSES if c not in classes]
    if missing:
        print(f"not found in defs: {', '.join(missing)}", file=sys.stderr)

    lines = [
        "--!nocheck",
        "-- GENERATED by tools/gen_mock_api.py from tools/globalTypes.d.luau.",
        "-- Do not edit. Per-class property names (inherited included) so the mock",
        "-- can reject an invalid property write the way Roblox does.",
        "--",
        "-- Deliberately a GLOBAL, not a module: the harness concatenates this",
        "-- ahead of the mock, and a chunk-level `return` would end the script.",
        "",
        "MOCK_API = {}",
        "",
    ]

    total = 0
    for name in CLASSES:
        if name not in classes:
            continue
        props = sorted(resolve(classes, name))
        total += len(props)
        body = ", ".join(f"{p} = true" for p in props)
        lines.append(f"MOCK_API.{name} = {{ {body} }}")

    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len([c for c in CLASSES if c in classes])} classes, {total} property entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
